replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: patient-documents
  tag: latest

service:
  type: ClusterIP
  port: 8099

autoscaling:
  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 5
  #  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

config:
  OPENMRS_HOST: openmrs

volumes:
  claimName: openmrs-document-images-pvc