apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.metadata.labels.environment }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/nginx/html/document_images
              name: openmrs-document-images
      restartPolicy: Always
      volumes:
        - name: openmrs-document-images
          persistentVolumeClaim:
            claimName: openmrs-document-images-pvc