apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: '8099'
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Chart.Name }}
    environment: {{ .Values.metadata.labels.environment }}
  type: {{ .Values.service.type }}
